### ISSUE TITLE
[ArrayView] const interator for normal iterator - bug?

### ISSUE THREAD

**Issue by mathisloge** [commschamp/comms_champion#10]
I have tried to copy some data into a data field. (ArrayView). But since all member functions are const, I cannot change the underlying data. 

Now there are two possibilities: Either I have missed something or it is an error that the [ArrayView.h#L77 ](https://github.com/commschamp/comms_champion/blob/master/comms/include/comms/util/ArrayView.h#L77 )
Iterator is marked as a const_iterator. 

For me this is a bit counterintuitive, because an iterator of some data should be modifiable.

**Comment by arobenko** [comment]
The original intention of adding `comms::field::ArrayView` was to have a const view on the original data, usually input buffer, which is passed to `read()` functions as some kind of const iterator / const pointer, to avoid unnecessary copying to the vector fields. Usage of such view when preparing message to be sent out is also allowed when the original buffer is going to outlive the message object. I usually work on such buffer directly and then assign it to the field right before the message is being sent:
```cpp
comms::util::assign(dataField.value(), buf.begin(), buf.end());
```
I haven't really had a need to allow modification of the buffer via the view. If you need to update the field value itself, why do you insist on using the "view" instead of proper std::vector storage?

**Comment by mathisloge** [comment]
Thanks for the `comms::util::assign(dataField.value(), buf.begin(), buf.end());`  didn't know such a function existed.

So it was the first case :)

**Comment by arobenko** [comment]
The `comms::util::assign()` function was introduced to allow storage type agnostic assignments. The problem is that types like `std::string` and `std::string_view` have different ways to assign values. For the "view" case the constructor in conjunctions with the copy assignment need to be used:
```cpp
strField.value() = std::string_view(buf, bufSize);
```
Similar is with raw data. See doc details of `comms::util::assign()` [here](https://commschamp.github.io/comms_doc/namespacecomms_1_1util.html#a8b2699905fdbe18d691e4cf30619c7cc).

Also I don't know whether you are aware, but some time ago I introduced a change that `comms::option::OrigDataView` forces usage of `std::string_view` or `std::span` as storage type if such exist. If not `comms::util::StringView` and `comms::util::ArrayView` respectively are chosen to be the storage types, which are expected to expose similar public interfaces. So the bottom line I recommend using `snake_case` member functions if applicable to allow easy transition to more modern compilers in the future.
